name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: sarutiwaskar.myddns.me  # Your server's hostname or IP address
          username: ubuntu  # The SSH user, typically "ubuntu" for EC2 instances
          key: ${{ secrets.EC2_SSH_KEY }}  # Secret key stored in GitHub secrets
          script: |
            cd /var/www/html  # Navigate to the project directory
            git pull origin main  # Pull the latest code from the main branch
            sudo chown -R www-data:www-data /var/www/html  # Set proper ownership
            sudo systemctl reload nginx  # Reload Nginx to apply changes

