name: Deploy WordPress

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H sarutiwaskar.myddns.me >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -i ~/.ssh/id_rsa ubuntu@sarutiwaskar.myddns.me "echo 'SSH connection successful!'"

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@sarutiwaskar.myddns.me <<EOF
            cd /var/www/html
            git pull origin main
            sudo chown -R www-data:www-data /var/www/html
            sudo systemctl reload nginx
          EOF





